# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-31 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dificultad',
            name='nivel_dificultad',
        ),
        migrations.AddField(
            model_name='dificultad',
            name='slug_dificultad',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
