# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-09 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20170131_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug_tipo',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipo',
            name='slug_tipo',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dificultad',
            name='slug_dificultad',
            field=models.CharField(max_length=50),
        ),
    ]
