# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-09 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20170209_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='slug_tipo',
            new_name='slug_categoria',
        ),
    ]
