# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-17 23:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0011_auto_20170217_1834'),
        ('base', '0004_auto_20170209_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='medida_ingrediente',
        ),
        migrations.DeleteModel(
            name='Ingrediente',
        ),
        migrations.DeleteModel(
            name='Medida',
        ),
    ]
