# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-28 21:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioReceta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario_receta', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='IngredienteReceta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Ingrediente')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_receta', models.CharField(max_length=80)),
                ('descripcion_receta', models.CharField(max_length=200)),
                ('calificacion_receta', models.IntegerField()),
                ('preparacion_receta', models.CharField(max_length=2000)),
                ('tiempo_preparacion_receta', models.CharField(max_length=5)),
                ('porciones_receta', models.CharField(max_length=2)),
                ('foto_receta', models.ImageField(upload_to='img/recetas/')),
                ('categoria_receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Categoria')),
                ('dificultad_receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Dificultad')),
                ('tipo_receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Tipo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ingredientereceta',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receta.Receta'),
        ),
        migrations.AddField(
            model_name='comentarioreceta',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receta.Receta'),
        ),
        migrations.AddField(
            model_name='comentarioreceta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
