# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-09 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='slug_receta',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
    ]
