# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-09 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0004_auto_20170209_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='calificacion_receta',
        ),
    ]
