# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-14 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0006_auto_20170209_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='descripcion_receta',
            field=models.CharField(max_length=500),
        ),
    ]
