# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-14 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0007_auto_20170214_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecetaPaso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_paso', models.CharField(max_length=1)),
                ('descripcion_paso', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='receta',
            name='preparacion_receta',
        ),
        migrations.AddField(
            model_name='recetapaso',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receta.Receta'),
        ),
    ]
