# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-14 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0008_auto_20170214_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetapaso',
            name='foto_paso',
            field=models.ImageField(default=0, upload_to='img/recetas/pasos/'),
            preserve_default=False,
        ),
    ]
