# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-17 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0010_auto_20170214_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientereceta',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='ingredientereceta',
            name='ingrediente',
        ),
        migrations.AddField(
            model_name='ingredientereceta',
            name='descripcion_ingrediente',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
