# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-25 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0014_auto_20170224_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='foto_receta',
            field=models.ImageField(blank=True, null=True, upload_to='img/recetas/'),
        ),
    ]
