# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-25 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0015_auto_20170224_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientereceta',
            name='descripcion_ingrediente',
            field=models.CharField(max_length=150),
        ),
    ]
