# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-26 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0016_auto_20170224_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recetapaso',
            options={'ordering': ['orden_paso']},
        ),
        migrations.AddField(
            model_name='receta',
            name='public_receta',
            field=models.BooleanField(default=True),
        ),
    ]
