# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-26 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0017_auto_20170226_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='categoria_receta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Categoria'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='descripcion_receta',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='dificultad_receta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Dificultad'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='nombre_receta',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='porciones_receta',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='slug_receta',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='tiempo_preparacion_receta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='tipo_receta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Tipo'),
        ),
    ]
