# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-28 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0018_auto_20170226_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='foto_receta',
            field=models.ImageField(blank=True, default='img/none.png', null=True, upload_to='img/recetas/'),
        ),
    ]
